apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: browmix-v5
  labels:
    app: flask
spec:
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: browmix-v5
        image: manojjahgirdar/browmix:v1.1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: browmix-service
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32222
  type: NodePort
